// Real browser workflow. NODE_PATH should include Playwright; no user project is touched.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
  const output=path.join(__dirname,'output/model-v1');fs.mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({channel:'msedge',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(120000);
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(process.env.REVIEW_URL||'http://127.0.0.1:8766/');
    await page.locator('#detect:not([disabled])').waitFor();
    const detection=page.waitForResponse(r=>r.url().endsWith('/api/detect'));
    await page.locator('#detect').click();const detected=await (await detection).json();
    await page.locator('#calibrate:not([disabled])').waitFor();
    await page.locator('#open-model').click();assert.equal(await page.locator('#model-dialog').isVisible(),false);
    await page.locator('#calibrate').click();
    const rect=await page.locator('#plan').boundingBox();
    await page.mouse.move(rect.x+rect.width*.2,rect.y+rect.height*.3);
    await page.mouse.down();await page.mouse.move(rect.x+rect.width*.6,rect.y+rect.height*.3,{steps:8});await page.mouse.up();
    await page.locator('#calibration-length').fill('6000');
    const calibration=page.waitForResponse(r=>r.url().endsWith('/api/model-settings'));
    await page.locator('#calibration-form button[type=submit]').click();
    const calibrated=await (await calibration).json();assert(calibrated.document.scale_mm_per_px>0);
    await page.locator('#open-model:not([disabled])').click();
    await page.locator('#model-canvas canvas').waitFor();
    assert.match(await page.locator('#model-summary').innerText(),/2800 mm/);
    const color=page.locator('[data-setting=wall_color]');await color.fill('#87a7bd');
    const settings=page.waitForResponse(r=>r.url().endsWith('/api/model-settings'));
    await page.locator('#apply-model').click();const applied=await (await settings).json();
    assert.equal(applied.document.model_settings.wall_color,'#87a7bd');
    await page.locator('#model-save:not([disabled])').waitFor();
    const saved=page.waitForResponse(r=>r.url().endsWith('/api/save-project'));
    await page.locator('#model-save').click();const save=await (await saved).json();
    const stored=JSON.parse(fs.readFileSync(path.join(__dirname,'projects',save.saved_name,'walls.json'),'utf8'));
    assert.equal(stored.model_settings.wall_color,'#87a7bd');assert.equal(stored.scale_mm_per_px,calibrated.document.scale_mm_per_px);
    await page.screenshot({path:path.join(output,'model-desktop.png')});
    await page.locator('[data-setting=window_height_mm]').fill('3000');
    await page.locator('#apply-model').click();assert.match(await page.locator('#model-message').innerText(),/不能大于墙高/);
    await page.locator('#model-discard').click();
    const undo=page.waitForResponse(r=>r.url().endsWith('/api/undo-edit'));
    await page.locator('#model-undo').click();const restored=await (await undo).json();assert.equal(restored.document.model_settings.wall_color,'#e4ddd3');
    await page.locator('#close-model:not([disabled])').click();
    await page.locator('#wall-layer g[role=button]').first().focus();
    await page.keyboard.press('Enter');
    await page.locator('#issue-type').selectOption('thickness');await page.locator('#amount').fill('16');
    const edit=page.waitForResponse(r=>r.url().endsWith('/api/apply-edit'));await page.locator('#add-issue').click();assert.equal((await edit).status(),200);
    await page.locator('#open-model:not([disabled])').click();await page.locator('#model-canvas canvas').waitFor();
    await page.locator('#model-top').click();
    await page.screenshot({path:path.join(output,'model-top.png')});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'model-mobile.png')});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    assert.equal(await page.locator('#model-dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({walls:detected.document.walls.length,calibration:true,model:true,color:true,save:true,undo:true,invalidHeight:true,editSync:true,mobile:true,errors}));
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
